project:
  type: book

crossref:
  lst-title: "Algorithm"
  lst-prefix: "Algorithm"

book:
  title: "The Algorithm Codex"
  author: "Alejandro Piad-Morffis, Ph.D."
  date: "1/18/2026"
  chapters:
    - index.qmd
    - 00_intro.qmd
    - part: part1.qmd
      chapters:
      - 01_search.qmd
      - 02_binary.qmd
      - 03_sort.qmd
      - 04_sort_fast.qmd
      - 05_rankings.qmd
      - 06_linear_sort.qmd
      - 07_sort_practice.qmd
      - lessons_1.qmd
    - part: part2.qmd
      chapters:
      - 08_memory.qmd
      - 09_linked.qmd
      - 10_stack.qmd
      - 11_queue.qmd
      - 12_hash.qmd
      - 13_bloom.qmd
      - 14_union_find.qmd
      - lessons_2.qmd
    - part: part3.qmd
      chapters:
      - 15_binary_trees.qmd
      - 16_bst.qmd
      - 17_avl.qmd
      - 18_treap.qmd
      - 19_heap.qmd
      - 20_trie.qmd
      - 21_segment.qmd
      - 22_fenwick.qmd
      - lessons_3.qmd
    - part: part4.qmd
      chapters:
      - 23_brute.qmd
      - 24_automaton.qmd
      - 25_kmp.qmd
      - 26_boyer_moore.qmd
      - 27_rabin_karp.qmd
      - 28_aho_corasick.qmd
      - 29_suffix_array.qmd
      - 30_edit_distance.qmd
      - lessons_4.qmd
    - part: part5.qmd
      chapters:
      - 31_graph_rep.qmd
      - 32_bfs.qmd
      - 33_dfs.qmd
      - 34_dijkstra.qmd
      - 35_relaxation.qmd
      - 36_mst.qmd
      - 37_topo_scc.qmd
      - 38_flow.qmd
      - lessons_5.qmd
    - part: Dynamic Programming and Greedy Algorithms
      chapters: []
    - part: Specialized Domains
      chapters: []
    - part: Advanced Complexity
      chapters: []
  appendices:
    - appendix-python.qmd
    - appendix-notation.qmd
    - appendix-math.qmd

toc-depth: 2
number-depth: 1

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    papersize: a4
    geometry:
      - margin=2cm
    fontsize: 10pt
    toc: true
    toc-depth: 2
    number-sections: true